export const PERSISTANCE_CONFIG = {
  COLLECTIONS_MODELS: false,
  DISPOSITIFS_POST_STORE: false,
  FICHE_TECHNIQUE_POST_STORE: false,
  GPS_SELECTED_THEMATIQUE_STORE: false,
  SEARCH_STORE: false,
}
